---
- name: Clone code
  git:
    repo: 'https://github.com/lamcm58/test_deploy_using_jenkins.git'
    dest: /var/www/laravel-app
    version: deve

- name: Render application .env securely
  template:
    src: templates/env.j2
    dest: /var/www/laravel-app/.env
    owner: www-data
    group: www-data
    mode: '0640'
  become: yes

- name: Install composer dependencies
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"
    COMPOSER_NO_INTERACTION: "1"
  command: composer install --no-dev --no-progress --prefer-dist --optimize-autoloader chdir=/var/www/laravel-app

- name: Run migrations
  command: php artisan migrate --force chdir=/var/www/laravel-app

- name: Clear cache
  command: php artisan optimize:clear chdir=/var/www/laravel-app

- name: Restart Apache2
  service:
    name: apache2.service
    state: restarted
  become: yes
