---
- name: Clone code
  git:
    repo: 'https://github.com/lamcm58/test_deploy_using_jenkins.git'
    dest: /var/www/laravel-app
    version: deve

# - name: Copy .env
#   template:
#     src: templates/env.j2
#     dest: /var/www/laravel-app/.env

- name: Install composer dependencies
  command: composer install --no-dev --optimize-autoloader chdir=/var/www/laravel-app

- name: Run migrations
  command: php artisan migrate --force chdir=/var/www/laravel-app

- name: Clear cache
  command: php artisan optimize:clear chdir=/var/www/laravel-app

# - name: Restart PHP-FPM
#   service:
#     name: php8.2-fpm
#     state: restarted
